### ISSUE TITLE
Con la instalación de paquetes adicionales puede hacer funcionar en Ubuntu Server 18.04.2

### ISSUE THREAD

**Issue by pabarrientos** [martinllanos/tallerdeodoo#1]
`sudo apt-get install lib32ncurses5 lib32z1`

esto me pasó a la hora de instalar aeroo y office

ya que a la hora de imprimir cualquier reporte de aeroo aún con los servicios funcionando en los puertos 8100 office y 8989 aeroo-docs, me tiraba todos los reportes un error del módulo aeroo-repors de ingadhoc en main.py line 90 no adjunto imagen porque ya no me dá el error... :-) Saludos!!!

**Comment by martinllanos** [comment]
Espectacular!!!. A mi, me esta funcionando sin esas librerias. Lo que hice es comprobarlo con apt list | grep lib32ncurses5 y no encotre estas librerias instaladas. Pero si ocn eso te funciona, genial!!!

**Comment by pabarrientos** [comment]
perdón... la dependencia para el funcionamiento era
`sudo apt install unoconv`
hacer esto despues de instalar los paquetes de libreoffice... Saludos!!!

**Comment by martinllanos** [comment]
Epectacular @pabarrientos
