### ISSUE TITLE
Error al instalar M2Crypto

### ISSUE THREAD

**Issue by eltioseba** [martinllanos/tallerdeodoo#2]
https://github.com/martinllanos/tallerdeodoo/blob/fe8a2baa342ee4c7c3d62b1bef2c91919ed48c1a/taller-de-odoo-002/taller-odoo-002.sh#L35

Hola, al correr ese comando me tiro "Running setup.py install for M2Crypto ... error". Y después un choclo.

Si no me equivoco es un problema de incompatibilidad de versiones, pero la verdad no tengo mucha idea.

saludos

pd. buenísimo el video, el script, todo, gracias!

**Comment by martinllanos** [comment]
Nos podrías contar que versión estás tratando de instalar y en qué sistema
operativo?

**Comment by eltioseba** [comment]
la v11 en Ubuntu 18 (Desktop)

**Comment by martinllanos** [comment]
Podrías pasarme el error por pastebin?

**Comment by eltioseba** [comment]
https://pastebin.com/gC2yKDDU

Ahora veo si logro instalarlo.

edit: pude instalarlo instalando antes libssl-dev swig python3-dev gcc
